export const MESSAGE_TYPES = {
  CONNECTED_TO_ROOM: "CONNECTED_TO_ROOM",
  DISCONNECTED_FROM_ROOM: "DISCONNECTED_FROM_ROOM",
  WAITTING_TURN: "WAITTING_TURN",
  HAS_LOST: "HAS_LOST",
};

export const EVENT_TYPES = {
  ADD_USER_TO_ROOM: "ADD_USER_TO_ROOM",
  PLAY_GAME: "PLAY_GAME",
  UPDATE_GAME: "UPDATE_GAME",
  SOMEONE_HAS_LOST: "SOMEONE_HAS_LOST",
};
